=== ExoSkye/celldk-exports/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "returns": {
      "type": "string"
    },
    "params": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "type",
          "description"
        ]
      }
    },
    "brief": {
      "type": "string"
    },
    "class": {
      "type": "string"
    },
    "firmwares": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "flags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    }
  },
  "required": [
    "id",
    "name",
    "returns",
    "params",
    "brief",
    "class",
    "firmwares",
    "flags"
  ]
}

=== ExoSkye/celldk-exports/specs/fs_read.json
{
  "name": "sys_fs_read",
  "id": 802,
  "returns": "CellFsErrno",
  "brief": "Read from a file descriptor",
  "class": "sys_fs",
  "params": [
    {
      "name": "fd",
      "type": "u32",
      "description": "The file descriptor"
    },
    {
      "name": "buf",
      "type": "void*",
      "description": "The buffer to write the data read from the file into"
    },
    {
      "name": "nbytes",
      "type": "u64",
      "description": "The length of 'buf'"
    },
    {
      "name": "nwritten",
      "type": "u64*",
      "description": "The variable to write the actual number of bytes read to"
    }
  ],
  "flags": [],
  "firmwares": [
    "CEX",
    "DEX",
    "DECR"
  ]
}

=== ExoSkye/celldk-exports/specs/process_get_sdk_version.json
{
  "name": "sys_process_get_sdk_version",
  "id": 25,
  "returns": "int",
  "brief": "Returns the SDK version of a process",
  "class": "sys_process",
  "params": [
    {
      "name": "pid",
      "type": "sys_pid_t",
      "description": "The PID of the process you want to get the SDK Version of"
    },
    {
      "name": "version",
      "type": "u32*",
      "description": "The pointer to the u32 which the SDK Version will be written to"
    }
  ],
  "flags": [
    "root"
  ],
  "firmwares": [
    "CEX",
    "DEX",
    "DECR"
  ]
}

=== ExoSkye/celldk-exports/specs/fs_rename.json
{
  "name": "sys_fs_rename",
  "id": 812,
  "returns": "CellFsErrno",
  "brief": "Rename a file",
  "class": "sys_fs",
  "params": [
    {
      "name": "path",
      "type": "const char* path",
      "description": "The path of the file to rename"
    },
    {
      "name": "to",
      "type": "const char*",
      "description": "The new path of the fail"
    }
  ],
  "flags": [],
  "firmwares": [
    "CEX",
    "DEX",
    "DECR"
  ]
}

=== ExoSkye/celldk-exports/specs/fs_open.json
{
  "name": "sys_fs_open",
  "id": 801,
  "returns": "CellFsErrno",
  "brief": "Opens a file",
  "class": "sys_fs",
  "params": [
    {
      "name": "path",
      "type": "const char*",
      "description": "The path of the file to open"
    },
    {
      "name": "flags",
      "type": "u32",
      "description": "The flags to open the file with"
    },
    {
      "name": "fd",
      "type": "u32*",
      "description": "The variable to write the resultant file descriptor to"
    },
    {
      "name": "arg",
      "type": "const void*",
      "description": "Miscellaneous arguments"
    },
    {
      "name": "size",
      "type": "u64",
      "description": "Length of the miscellaneous arguments"
    }
  ],
  "flags": [],
  "firmwares": [
    "CEX",
    "DEX",
    "DECR"
  ]
}

=== ExoSkye/celldk-exports/specs/fs_close.json
{
  "name": "sys_fs_close",
  "id": 804,
  "returns": "CellFsErrno",
  "brief": "Closes a file descriptor",
  "class": "sys_fs",
  "params": [
    {
      "name": "fd",
      "type": "u32",
      "description": "The file descriptor to close"
    }
  ],
  "flags": [],
  "firmwares": [
    "CEX",
    "DEX",
    "DECR"
  ]
}

=== ExoSkye/celldk-exports/specs/tty_read.json
{
  "id": 402,
  "name": "sys_tty_read",
  "returns": "s32",
  "params": [
    {
      "name": "ch",
      "type": "u32",
      "description": "The TTY channel to read from"
    },
    {
      "name": "buf",
      "type": "void*",
      "description": "The buffer to read into"
    },
    {
      "name": "len",
      "type": "u32",
      "description": "The length of `buf`"
    },
    {
      "name": "preadlen",
      "type": "u32*",
      "description": "Pointer to an u32 to put the amount of data read"
    }
  ],
  "brief": "Read from the tty",
  "class": "sys_tty",
  "firmwares": [
    "DECR",
    "DEX",
    "CEX"
  ],
  "flags": []
}

=== ExoSkye/celldk-exports/specs/fs_unlink.json
{
  "name": "sys_fs_unlink",
  "id": 814,
  "returns": "CellFsErrno",
  "brief": "Deletes a file",
  "class": "sys_fs",
  "params": [
    {
      "name": "path",
      "type": "const char*",
      "description": "The path of the file to delete"
    }
  ],
  "flags": [],
  "firmwares": [
    "CEX",
    "DEX",
    "DECR"
  ]
}
